version: 2
jobs:
  build:
    working_directory: /home/circleci/SupermarKit
    docker:
      - image: danreynolds/supermarkit_circle:1.0.0
        environment:
          RAILS_ENV: test
          RACK_ENV: test
      - image: circleci/mysql
    steps:
      - checkout
      - run:
          name: Use Circle Database Config
          command: cp config/{database_circleci,database}.yml
      - run:
          name: Setup Dependencies and Database
          command: |
            bundle install
            bundle exec rake db:setup --trace
      - run:
          name: Run Tests
          command: rspec
