version: 2
jobs:
  build:
    working_directory: /home/circleci/SupermarKit
    docker:
      - image: danreynolds/supermarkit_circle:1.0.1
        environment:
          RAILS_ENV: test
          RACK_ENV: test
          DEPLOY_TAG: ${CIRCLE_BUILD_NUM}_${CIRCLE_SHA1:0:7}

      - image: circleci/mysql
    steps:
      - checkout
      - run:
          name: Use Circle Database Config
          command: cp config/{database_circleci,database}.yml
      - run:
          name: Setup Dependencies and Database
          command: |
            bundle install
            bundle exec rake db:setup --trace
      - run:
          name: Run Tests
          command: rspec


      - deploy:
          name: Deploy Check
          command: |
            if [ "${CIRCLE_BRANCH}" != "master" ]; then
              exit 1
            fi

      # Activate the Remote Docker Environment
      - setup_remote_docker

      - deploy:
          name: Deploy to Production
          command: |
            docker build -f Dockerfile.prod -t danreynolds/supermarkit:$DEPLOY_TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push danreynolds/supermarkit:$DEPLOY_TAG
