version: 2
jobs:
  build:
    working_directory: /home/circleci/SupermarKit
    docker:
      - image: danreynolds/supermarkit_circle:1.0.1
        environment:
          RAILS_ENV: test
          RACK_ENV: test

      - image: circleci/mysql
    steps:
      - checkout
      - run:
          name: Use Circle Database Config
          command: cp config/{database_circleci,database}.yml
      - run:
          name: Setup Dependencies and Database
          command: |
            bundle install
            bundle exec rake db:setup --trace
      - run:
          name: Run Tests
          command: rspec

      - deploy:
          name: Deploy Check
          command: |
            if [ "${CIRCLE_BRANCH}" != "master" ]; then
              exit 0
            fi

      # Activate the Remote Docker Environment
      - setup_remote_docker

      - deploy:
          name: Use Production Database Config
          command: cp config/{database.yml.sample,database.yml}

      - deploy:
          name: Load Environment File
          command: bundle exec rake secrets:decrypt

      - deploy:
          name: Deploy to Production
          command: |
            export DEPLOY_TAG="${CIRCLE_BUILD_NUM}_${CIRCLE_SHA1:0:7}"
            docker build -f Dockerfile.prod -t danreynolds/supermarkit:$DEPLOY_TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push danreynolds/supermarkit:$DEPLOY_TAG
            docker-compose -f docker-compose.yml -f docker-compose.production.yml run app rake docker:deploy
