version: '3'
services:
  app:
    volumes:
      - assets:/app/public/assets/
    image: danreynolds/supermarkit:$DEPLOY_TAG
    environment:
      - SECRET_KEY_BASE=dd049c1592063baf0f259f48e07f38b108f164277821db0fed37844dfd5002a2f8710d95a6dfe8a7aeeafaf22b794471004570dc106a0676f16dd1cfbb20a3e1
    depends_on:
      - db
  nginx:
    ports:
      - 80
    volumes:
      - /etc/letsencrypt/live/supermarkit.org/fullchain.pem:/etc/nginx/fullchain.pem
      - /etc/letsencrypt/live/supermarkit.org/privkey.pem:/etc/nginx/privkey.pem
      - /etc/ssl/certs/dhparam.pem:/etc/nginx/dhparam.pem
      - ./nginx.production.conf:/etc/nginx/conf.d/default.conf
    networks:
      default:
      nginx_default:
        aliases:
          - SUPERMARKIT
volumes:
  assets:
networks:
  nginx_default:
    external: true
