version: '3'
services:
  app:
    image: danreynolds/supermarkit:1.0.6
    volumes:
      - assets:/app/public/assets/
    environment:
      - SECRET_KEY_BASE=dd049c1592063baf0f259f48e07f38b108f164277821db0fed37844dfd5002a2f8710d95a6dfe8a7aeeafaf22b794471004570dc106a0676f16dd1cfbb20a3e1
    ports:
      - "3000:3000"
    depends_on:
      - db
  nginx:
    image: nginx
    depends_on:
      - app
    ports:
      - 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      default:
      nginx_default:
        aliases:
          - SUPERMARKIT
volumes:
  assets:
networks:
  nginx_default:
    external: true
