version: '3'
services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: root
    image: mariadb
  web:
    build: .
    volumes:
      - .:/SupermarKit
    ports:
      - "3000:3000"
    depends_on:
      - db
