version: '3'
services:
  app:
    env_file:
      - .env
    ports:
      - 3000
    depends_on:
      - db
  db:
    volumes:
     - /lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    image: mariadb
  nginx:
    image: nginx
    depends_on:
      - app
