version: '3'
services:
  app:
    volumes:
      - ./.env:/app/.env
      - assets:/app/public/assets/
      - logs:/app/log/
    image: danreynolds/supermarkit:$DEPLOY_TAG
    environment:
      - ENV_KEY=$ENV_KEY
      - DEPLOY_TAG=$DEPLOY_TAG
    depends_on:
      - db
  nginx:
    ports:
      - 80
    networks:
      default:
      nginx_default:
        aliases:
          - SUPERMARKIT
    volumes:
      - logs:/etc/nginx/log/
      - assets:/app/public/assets/
      - ./nginx.upstream.conf:/etc/nginx/conf.d/default.conf
volumes:
  assets:
  logs:
networks:
  nginx_default:
    external: true
