version: '3'
services:
  db:
    networks:
      - webnet
    environment:
      MYSQL_ROOT_PASSWORD: root
    image: mariadb
  web:
    links:
      - db
    image: danreynolds/supermarkit:1.0.2
    networks:
      - webnet
    volumes:
      - .:/SupermarKit
    ports:
      - "3000:3000"
    depends_on:
      - db
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
networks:
  webnet:
