version: '3'
services:
  app:
    image: danreynolds/supermarkit:$DEPLOY_TAG
    # Expose makes the internal port in the container available to other services
    # (like nginx) without publishing them to the host machine like in a ports mapping
    expose:
      - 3000
    environment:
      - SECRET_KEY_BASE=dd049c1592063baf0f259f48e07f38b108f164277821db0fed37844dfd5002a2f8710d95a6dfe8a7aeeafaf22b794471004570dc106a0676f16dd1cfbb20a3e1
    depends_on:
      - db
  nginx:
    image: nginx
    depends_on:
      - app
    ports:
      - 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      default:
      nginx_default:
        aliases:
          - SUPERMARKIT
networks:
  nginx_default:
    external: true
